### ISSUE TITLE
scroll

### ISSUE THREAD

**Issue by Devc2** [LukynkaCZE/better-saved-hotbars#1]
the orignal saved hotbars has 9 rows (scrollable)
but this has 6 rows
please fix this issue

**Comment by LukynkaCZE** [comment]
Will fix in next release, thanks for reporting!

**Comment by yorik100** [comment]
> Will fix in next release, thanks for reporting!

Could you also make the inventory infinitely big? For example, if there is an item in any of the 9 slots in the last row then add 9 to the size of the container or something around these lines.

**Comment by LukynkaCZE** [comment]
> Could you also make the inventory infinitely big? For example, if there is an item in any of the 9 slots in the last row then add 9 to the size of the container or something around these lines.

Oh yeah that's good idea! I cant probably do it infinite cause at some point opening that tab would lag your game but I can probably make it like 100 rows

**Comment by LukynkaCZE** [comment]
> Could you also make the inventory infinitely big? For example, if there is an item in any of the 9 slots in the last row then add 9 to the size of the container or something around these lines.

Okay so I lied, Minecraft has it forcefully set to 9 maximum when the class loads. There is probably work around but I'm not too familiar with mixins to figure it out, ill look into it more later but for now the issue with not being able to scroll is fixed
