### ISSUE TITLE
conflicts with mod remove reloading screen

### ISSUE THREAD

**Issue by FireInstall** [LukynkaCZE/better-saved-hotbars#17]
> > +conflicts with mod remove reloading screen
> 
> Do you have any crashlog? I can't see any problem besides the Minecraft version one.

[crash-2024-03-12_18.53.06.6204-quilt_loader.txt](https://github.com/LukynkaCZE/better-saved-hotbars/files/14575267/crash-2024-03-12_18.53.06.6204-quilt_loader.txt)

_Originally posted by @FaNToMaSikkk in https://github.com/LukynkaCZE/better-saved-hotbars/issues/11#issuecomment-1991990914_

**Comment by FireInstall** [comment]
As far as I can tell from the crash report, the breaking point is the mixin transformation of `net/minecraft/client/gui/screens/LoadingOverlay` - a class untouched by this mod - but (as the report states) dark loading screen.
`Remove reloading screen` nor `better saved hotbars` are mentioned in the stacktrace.

I tested with the following configuration:
- Minecraft 1.20.2
- fabric 0.15.7 / quilt loader 0.23.1
- better saved hotbars 1.1.1 (my 1.20.2 branch)
- cloth config api 12.0.119
- dark loading screen 1.6.14
- quilted fabric api 8.0.0-alpha.3/4
- remove reloading screen 3.2.4

and I couldn't get a crash nor an error. Your modlist is way too big for me to dig in and try every combination of mods just to find one that might or might not break. It would really help, if you can give a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) - the smallest modset that still crashes.

However, since there isn't an official version of this mod please use my **[unofficial version](https://github.com/FireInstall/better-saved-hotbars/releases/tag/1.1.2)** in the meantime to do your testing, as 1.20.2 can't work with an unupdated version of `better saved hotbars` regardless of mod incompatibility!

**Comment by FireInstall** [comment]
@FaNToMaSikkk

**Comment by FaNToMaSikkk** [comment]
> As far as I can tell from the crash report, the breaking point is the mixin transformation of `net/minecraft/client/gui/screens/LoadingOverlay` - a class untouched by this mod - but (as the report states) dark loading screen. `Remove reloading screen` nor `better saved hotbars` are mentioned in the stacktrace.
> 
> I tested with the following configuration:
> 
>     * Minecraft 1.20.2
> 
>     * fabric 0.15.7 / quilt loader 0.23.1
> 
>     * better saved hotbars 1.1.1 (my 1.20.2 branch)
> 
>     * cloth config api 12.0.119
> 
>     * dark loading screen 1.6.14
> 
>     * quilted fabric api 8.0.0-alpha.3/4
> 
>     * remove reloading screen 3.2.4
> 
> 
> and I couldn't get a crash nor an error. Your modlist is way too big for me to dig in and try every combination of mods just to find one that might or might not break. It would really help, if you can give a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) - the smallest modset that still crashes.
> 
> However, since there isn't an official version of this mod please use my **[unofficial version](https://github.com/FireInstall/better-saved-hotbars/releases/tag/1.1.2)** in the meantime to do your testing, as 1.20.2 can't work with an unupdated version of `better saved hotbars` regardless of mod incompatibility!


I used the same combination, and I tried it also with a full set of mods.
With the combination you wrote + with your mod version, only one mod causes an error, that is Accurate Block Placement Reborn.
With the full set of mods, only Accurate Block Placement Reborn is fine too.

[crash-2024-03-12_22.47.11.6167-quilt_loader.txt](https://github.com/LukynkaCZE/better-saved-hotbars/files/14577979/crash-2024-03-12_22.47.11.6167-quilt_loader.txt)

[Test vidio](https://youtu.be/ZZKYbSEywDs)

**Comment by FireInstall** [comment]
Just a heads-up: I will use acronyms of all the mods since I can't be bothered to type them all out every time I mention them.

👍 Now I can finally reproduce your error! Thank you very much!
But I can conclude your error does nothing have to do with `better saved hotbars`. The same crash happened whenever or not better saved hotbars is installed or not.
It's the conflict between `dark loading screen`(DLS) and `remove reloading screen`(RRS). It's because of a racing condition (whatever mod applies it's mixins the fastest), and does kinda makes sense: DLS tries to replace a variable that RRS completely removes. Most of the time DLS is faster (just because of the name I guess) but some dark Mixin Magic in `Accurate Block Placement Reborn` stalls DLS and there is nothing left to replace anymore.
It happens every odd moon with just the two mods but most of the time they **seem** to work fine together when they are really not. I'm pretty sure the duration config of DLS breaks.
This might be solvable by the author of DLS if they want mod compatibility with RRS. They stated in their source code that they plan to get DLS more compatible with other mods.

However, think about it: What do you expect to happen? Why do you need both DLS and RRS what does one do, that the other doesn't? They are both very similar, and maybe it's easier for you to just one of them or one mod could implement what it is missing in your eyes?
I suggest you open an issue in one (or both) of the mods repos:
[https://github.com/A5b84/dark-loading-screen/issues](https://github.com/A5b84/dark-loading-screen/issues)
[https://github.com/dima-dencep/rrls/issues](https://github.com/dima-dencep/rrls/issues)
