### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by FaNToMaSikkk** [LukynkaCZE/better-saved-hotbars#22]
Hello, please remove update notification from main menu to mod menu like another mods. Main menu is not place for this notify
![изображение](https://github.com/LukynkaCZE/better-saved-hotbars/assets/114670824/33076b92-0a05-4387-9b77-feb696c6e911)
![изображение](https://github.com/LukynkaCZE/better-saved-hotbars/assets/114670824/2f9e89de-1e21-4afe-b0ab-e710a0d30953)

**Comment by Terriwin** [comment]
How could you even think of that?

**Comment by Terriwin** [comment]
even after the update, the notification in the main menu did not disappear

**Comment by DaniDipp** [comment]
Same here. I'm using the most up to date mod version for my minecraft version (bsh 1.2.1 for minecraft 1.20.6). **Please don't show be an update notification for a different Minecraft version.** I will update to MC1.21 when my server does, not when one of my mods does.
