### ISSUE TITLE
[BUG]Creating Backpack Roller Failure

### ISSUE THREAD

**Issue by surfishs** [LukynkaCZE/better-saved-hotbars#4]
Better Saved Hotbars 1.1.0
You mention in this version that you fixed the scroll wheel, but I don't know what you fixed.
All I've found is that this version update has caused me to not be able to use the scroll wheel in the normal creation backpack screen.

**Comment by surfishs** [comment]
@LukynkaCZE

**Comment by LukynkaCZE** [comment]
Hi! Sorry for not getting to this sooner, I was busy with work. This should be fixed now (#7)
