### ISSUE TITLE
no scroll bar in the saved tool bar tab

### ISSUE THREAD

**Issue by krispyking24** [LukynkaCZE/better-saved-hotbars#9]
mc version is 1.19.4 and BSH version is 1.0.0, also maybe make it possible to move the arrow/button things to the other side 
![image](https://github.com/LukynkaCZE/better-saved-hotbars/assets/77263183/fc407d2a-97d9-44ec-9d11-8cea5ed79746)
![image](https://github.com/LukynkaCZE/better-saved-hotbars/assets/77263183/5bb56726-8b4d-40c1-9102-c01668b77210)

**Comment by LukynkaCZE** [comment]
Hi! Please make sure you are running the latest version (1.1.2 which is only for 1.20.1)
Also, the arrows and save icon are not from my mod, probably some other mod you have

**Comment by krispyking24** [comment]
is the fix for the scroll bar not simple to back port?, also is it not bsh that adds the other saved hotbars? i thought it was, sorry for that

**Comment by LukynkaCZE** [comment]
No its not hard to backport in this case specifically but everything has moreso moved to 1.20 at this point, would recommend just updating
